
import des1 from '../assets/cultural/bandapocalypse.png';
import des2 from '../assets/cultural/bhairavi.png';
import des3 from '../assets/cultural/farzimushaira.png';
import des4 from '../assets/cultural/fashionista.png';
import des5 from '../assets/cultural/flashmob.png';
import des6 from '../assets/cultural/focus fest ka text change karo.png';
import des7 from '../assets/cultural/framebyframe.png';
import des8 from '../assets/cultural/freshers.png';
import des9 from '../assets/cultural/jashn.png';
import des10 from '../assets/cultural/mehgheshree.png';
import des11 from '../assets/cultural/miniogvlogverse.png';
import des12 from '../assets/cultural/muktswar.png';
import des13 from '../assets/cultural/openmic.png';
import des14 from '../assets/cultural/razmataaz.png';
import des15 from '../assets/cultural/ReelitReal.png';
import des16 from '../assets/cultural/symphonica.png';
import des17 from '../assets/cultural/kalasparsh.png';
import des18 from '../assets/cultural/marathidrama.png';


const culturalEvents = [
    { id: 1, title: "Band Apocalypse || 12TH Feb", description: "Band Apocalypse – The Ultimate Band Showdown! Get ready to rock the stage at Beats and Battles, the electrifying band competition of Yash 25.0! Whether you're a group of seasoned performers or an emerging crew, this is your moment to make the crowd roar and claim victory. ", image: des1 , link : "https://forms.gle/MRZvfwaQa9y5pN5J9"},
    { id: 2, title: "Bhairavi || 15TH Feb", description: "Get ready for an unforgettable experience at Bhairavi, the annual cultural extravaganza on 15th February, starting from 11:00 AM onwards! 🎉✨ Join us for a vibrant celebration of talent, featuring mesmerizing dance💃, soul-stirring music🎶, and captivating drama🎭. It’s a day full of creativity, energy, and passion you won’t want to miss! 🎇🎤 Let the magic unfold at YCCE!", image: des2 ,link : "https://www.yash2k25.tech/"},
    { id: 3, title: "Farzi Mushaira || 13TH Feb", description: "Come and enjoy a fun-filled evening at the Farzi Mushaira during Yash 25.0 at YCCE! 🌟 On 13th February, starting from 2:00 PM onwards, get ready for a blend of humor, creativity, and some quirky poetry! ✍💫 Our poets will bring their unique style and add a touch of fun to traditional shayari. It’s going to be a relaxed and lively session you won’t want to miss! 🎉", image: des3 ,link : "https://www.yash2k25.tech/"},
    { id: 4, title: "Fashionista || 14TH Feb", description: "Fashionista - Step Up and Own the Ramp! Calling all fashion enthusiasts! The Fashionista at Yash 25.0 are open to everyone who dreams of ruling the runway. Whether you're here to slay in style or charm the audience with confidence, this is your moment to shine", image: des4 ,link : "https://forms.gle/87JDwB3Vy9ueaA8n7"},
    { id: 5, title: "Flash Mob 2k25 || 10TH Feb", description: "Get ready to be blown away! 🎉 On 10th February, from 4:00 PM onwards, Yash 25.0 at YCCE is bringing you a mind-blowing Flashmob! 🌟 Watch as students suddenly break into epic moves, turning the space into a dance floor full of energy and excitement! 🔥💫 It's going to be spontaneous, thrilling, and absolutely unforgettable! Don’t miss the hype—be there and be amazed! 🎶✨", image: des5 ,link : "https://www.yash2k25.tech/"},
    { id: 6, title: "Focus Fest || 12TH Feb", description: "Capture the moment, tell the story and Unleash your inner photographer and showcase your talent through the lens in the Focus Fest ! Whether it's the beauty of streets or the elegance of architecture, let your creativity shine.(Submit till 12th Feb) ", image: des6 ,link : "https://forms.gle/KGDoH37eLFL1UjwE9"},
    { id: 7, title: "Frame By Frame", description: "FRAME BY FRAME – A Short Film Competition Like No Other! 🎬  Get ready for the exciting short film competition at Yash 2025! Whether you're an aspiring filmmaker or a seasoned director, this is your chance to showcase your creativity and storytelling skills.", image: des7 ,link : "https://forms.gle/XoCCarjvKHZpwU1Y6"},
    { id: 8, title: "Freshers 2k25 || 12TH Feb", description: "Hey, freshers! Your journey begins here, and we’re rolling out the red carpet for YOU! Get ready for a thrilling day of nonstop fun, electrifying vibes, and unforgettable moments. This isn’t just an event—it’s your grand debut into college life, packed with excitement, surprises, and endless laughter! 🥳From pulse-pounding games to jaw-dropping performances, and a stage waiting for you to shine, this event is all about celebrating your arrival in style. So, gather your energy, bring your enthusiasm, and let’s make this the start of something amazing! 🤩", image: des8 ,link : "https://forms.gle/MRZvfwaQa9y5pN5J9"},
    { id: 9, title: "Jashn E Mehfil || 13Th Feb", description: "Get ready to dive into an evening of soulful melodies at Jashn-e-Mehfil during Yash 25.0 at YCCE! 🌟 Join us on 13th February, from 2:30 PM to 5:00 PM, for a musical extravaganza that will leave you captivated by stunning performances and rhythmic beats. 🎤🎶 Let the music take you on a journey of pure magic and bliss! Don’t miss this melodious celebration! ✨", image: des9 ,link : "https://www.yash2k25.tech/"},
    { id: 10, title: "Megheshree || 14TH Feb", description: "🏋‍♂ MEGHESHREE 2025 – Bodybuilding & Fitness Competition🏆 Showcase your strength, fitness, and passion for bodybuilding at MEGHESHREE 2025! This exciting competition offers a platform for athletes to compete, inspire, and leave a mark. Whether you’re into bodybuilding, physique competitions, or fitness modeling, there’s a category for everyone.", image: des10 ,link : "https://forms.gle/dSXpRWVsb4WBqo1u5"},
    { id: 11, title: "Mini Vlogverse", description: "Get ready to showcase your talent , creativity and Capturing Your Own Moment, Create Memories Forever through Mini Vlog Making Competition! 🌟 This is your moment to shine with a short, impactful vlog that tells your fun story.💥", image: des11 ,link : "https://forms.gle/km9YrpVdPYY4A9GH8"},
    { id: 12, title: "Mukt Swar || 7TH Feb", description: "🎭 Mukt Swar – Unleash the Power of Expression! 🎙  Showcase your dramatic flair at Mukt Swar, the Online Monologue, Story Telling and Mimicry Competition of Yash 25.0! Whether you're a master of emotions or a mimicry maestro, this is your chance to captivate the audience.", image: des12 ,link : "https://forms.gle/4BmELhYvtfoFDEzk8"},
    { id: 13, title: "Open Mic || 12TH Feb", description: "🎤 Open Mic – Let Your Voice Be Heard! 🎙 Step up, speak out, and captivate the crowd at Open Mic, the most awaited platform of Yash 25.0! Share your stories, poetry, or jokes and make the audience feel your vibe.  ", image: des13 ,link : "https://forms.gle/S84Cz7UPqd6KWspd9"},
    { id: 14, title: "Raaz Matazz || 14TH Feb", description: "💃 Raaz Matazz – Where Moves Speak Louder Than Words! 🕺  Get ready to groove and dazzle the crowd at Raaz Matazz, Yash 25.0’s ultimate dance competition—solo, duo, or team, the stage is yours! 💃🕺", image: des14 ,link : "https://forms.gle/ae9bHjuT9AAydqvw8"},
    { id: 15, title: "Reel It Real", description: "🤳🏻  REEL IT REAL 🤳🏻'Unleash your creativity' Are you ready to captivate the world with your creativity ❓ Join our Reel Making Competition and showcase your talent in crafting engaging and impactful reels ✨🤳🏻", image: des15 ,link : "https://forms.gle/BLX2NeNig2Bkwx4u9"},
    { id: 16, title: "Symphonica || 13TH Feb", description: "🎤 Symphonica – Where Voices Create Magic! 🎶Unleash the melody within you and take center stage at Symphonica , the singing competition that’s set to steal hearts at Yash 25.0! Whether you’re a solo powerhouse or a dynamic duo, this is your chance to shine and claim the spotlight.", image: des16 ,link : "https://forms.gle/1ZF5WSt783rHcjrz9"},
    { id: 17, title: "Kalasparsh || 13TH Feb", description: "Step into a world of creativity and expression at Kalasparsh: The Art Club Exhibition!* 🎭 Whether you're an artist or an admirer, this is your chance to witness stunning artworks and immerse yourself in the beauty of artistic talent. ", image: des17 ,link : "https://docs.google.com/forms/d/e/1FAIpQLSeuKd1fmBi1OWMGNPbh2VDkzzXcHy0kPpfyB8SbF3l0lrvG2g/viewform"},
    { id: 18, title: "Marathi Drama || 13TH Feb", description: "Lights, camera, action! 🎬✨ Get ready to be swept off your feet with a stunning Marathi Drama on 13th February from 10:00 AM to 12:00 PM at YCCE! 🌟 Experience the magic of storytelling, packed with emotions, drama, and cultural flair. Don’t miss this exciting, unforgettable performance at Yash 25.0!", image: des18 ,link : "https://forms.gle/1ZF5WSt783rHcjrz9"}
  ];
  
  export default culturalEvents;
  