import des1 from '../assets/Technical/avishkar.png';
import des2 from '../assets/Technical/blueprinttobridge.png';
import des3 from '../assets/Technical/buzzwire.png';
import des4 from '../assets/Technical/codeandcanvas.png';
import des5 from '../assets/Technical/codeista.png';
import des6 from '../assets/Technical/cognitive.png';
import des7 from '../assets/Technical/debate.png';
import des8 from '../assets/Technical/enigma.png';
import des9 from '../assets/Technical/ieeworkshop.png';
import des10 from '../assets/Technical/lasergun.png';
import des11 from '../assets/Technical/microsoftwebinar.png';
import des12 from '../assets/Technical/nocodeai.png';
import des13 from '../assets/Technical/pcbnexus.png';
import des14 from '../assets/Technical/resumeit.png';
import des15 from '../assets/Technical/robosoccer.png';
import des16 from '../assets/Technical/techartfusion.png';
import des17 from '../assets/Technical/turningtussle.png';
import des18 from '../assets/Technical/visualvibes.png';

const technicalEvents = [
    { id: 1, title: "Avishkar || 5TH - 9TH Feb", description: "Unleash your scientific creativity and artistic skills! 🌟 Participate in Avishkar, a technical platform featuring a Science Model Competition for school students", image: des1 ,link : "https://docs.google.com/forms/d/e/1FAIpQLSeKXXT2sffKnGQ5x9eBAzdhYC2hUfaOOA-P6N7MIw8XGhKBAg/viewform?usp=header"},
    { id: 2, title: "Blueprint to Bridge || 14TH Feb", description: "Unleash your creativity and engineering skills at the Blueprint to Bridge competition under Yash 25.0! Get ready to design and construct a bridge with limited materials, testing its strength and innovation in real-world weight challenges.", image: des2 ,link : "https://docs.google.com/forms/d/e/1FAIpQLSecx68r53Hp65xYw0f9sLHz8dsV-qWOAYuxapYmkgKT_gaxiA/viewform?usp=header"},
    { id: 3, title: "Buzz Wire || 14th Feb", description: "Hey Challengers! 🎉 Are you ready to put your skills to the test at the Buzz Wire Challenge 2025!? Prove your precision and steady hands for a chance to claim victory and exciting prizes!", image: des3 ,link : "https://docs.google.com/forms/d/e/1FAIpQLSeke8aKtu_eC9M0STX0GYJLrzsCE_ZNihXY7SgcV0XdqS2TEA/viewform?usp=header"},
    { id: 4, title: "Code and Canvas || 14TH Feb", description: "Are you ready to take on the challenge? 🤩 You’ll craft a stunning, responsive UI/UX that adapts flawlessly across all devices! ✨🎨 With a sleek, user-friendly design, smooth animations, and intuitive navigation, the experience will be seamless. 🚀 No backend needed—just clean, efficient front-end code to bring it to life with speed and functionality. ⚡💻 Let’s build something amazing! 🎉", image: des4 ,link : "https://docs.google.com/forms/d/e/1FAIpQLScIm4gFI81IY79LEqE_UiGWVSbvI-LEPN2DhuY3sIQvOJRPCw/viewform?usp=header"},
    { id: 5, title: "Codista || 15TH Feb", description: "🚀 Ready to take your coding skills to the next level? Join Codista , the ultimate coding competition where you can put your problem-solving and coding expertise to the test! Whether you're a programming pro or a budding coder, this challenge is the perfect platform to showcase your talent, compete for incredible prizes, and sharpen your coding abilities!", image: des5 ,link : "https://docs.google.com/forms/d/e/1FAIpQLSdb9K9Rc6tgG2kVsOtq4dsX1lI7Bb6kfQpdeaJIabXY8eehrA/viewform?usp=header"},
    { id: 6, title: "Cognitive Clash || 12TH Feb", description: "Test your knowledge and compete against the brightest minds in Cognitive Clash, an inter-college quiz competition designed to challenge your intellect across a wide range of topics. Whether you’re a trivia enthusiast or just enjoy a good challenge, this event is for you.", image: des6 ,link : "https://docs.google.com/forms/d/e/1FAIpQLSeVxVBjrnXRJlyIu-XRb_nuN1iJhdBrOM094BM-Y58bxczqHw/viewform?usp=header"},
    { id: 7, title: "Debate || 10TH Feb", description: "Showcase your intellect and oratory skills at the Debate Competition under Yash 25.0, at YCCE! Engage in thought-provoking discussions and outshine your opponents with logic and confidence.  ", image: des7 ,link : "https://docs.google.com/forms/d/e/1FAIpQLSeyPVO9lkpBlkZhHhtg0QsbKece82K-oAT4Cr9hd3jbFFchOA/viewform?usp=header"},
    { id: 8, title: "Enigma || ", description: "Are you ready to solve real-world problems with your coding skills? Join the Hackathon, a thrilling event under Yash 25.0, where teams will compete to create innovative solutions in a limited time. Whether you're a seasoned coder or a passionate beginner, this is your chance to collaborate, innovate, and showcase your skills!", image: des8 ,link : "https://docs.google.com/forms/d/e/1FAIpQLScH8y83S440b_q0LE-i8XfkasI6j5hXk96fSc9vTnYIyBtwYQ/viewform?usp=header"},
    { id: 9, title: "IEEE Workshop || 13TH Feb", description: "Hey Future Engineers! 🚀 Join us for an exclusive *IEEE Workshop* and explore *cutting-edge technology, innovation, and real-world applications!*  ", image: des9 ,link : "https://docs.google.com/forms/d/e/1FAIpQLSe2XRtTczKIXSXRugGBRf1Sl5NLdnMQgh2-zN309JvTGNfebQ/viewform?usp=header"},
    { id: 10, title: "Lasergun || 13TH Feb", description: "Step into the thrill zone at Yash 25.0 with the Laser Battle Arena, where precision, strategy, and adrenaline collide! Compete, conquer, and show your dominance in this electrifying laser gun challenge.  ", image: des10 ,link : "https://docs.google.com/forms/d/e/1FAIpQLSfsYlx-Plj5C1KE0CQmn68Is4QdfbhMZHuxHuBkY1MdmWydHQ/viewform?usp=header"},
    { id: 11, title: "Microsoft Webinar || 9TH Feb", description: "Hey Tech Enthusiasts! 🎉 Get ready for an exclusive Microsoft Tech Webinar, where you'll explore the latest advancements in Cloud Computing, AI, and Software Development– all in an interactive offline session!  ", image: des11 ,link : "https://docs.google.com/forms/d/e/1FAIpQLSd7_bgzacX9rn3O-WiQ7yorh19R_N3s9z1Q7BH486-4c87vtg/viewform?usp=header"},
    { id: 12, title: "No Code AI || 14th Feb", description: "🚀 NoCode AI Innovators – Build App / Website Without Coding! 🤖Hey Innovators! 🎉 Join us for NoCode AI Innovators, Got a brilliant idea but don’t know how to code? No, CodeAI Innovators is for you!  This is the ultimate no-code challenge where you get to bring your idea to life—without writing a single line of code. Whether you're a creative mind or just love problem-solving, this event is your chance to build something cool, showcase your skills, and win awesome prizes.", image: des12 ,link : "https://docs.google.com/forms/d/e/1FAIpQLScK5WBptLJr6KtrL4QqGQVOwXscHp-mvOVWSSMI9J6YuK1r2g/viewform?usp=header"},
    { id: 13, title: "PCB Nexus || 13TH Feb", description: "Hello Innovators! 🎉 Get ready for an exciting opportunity to dive deep into the world of Printed Circuit Boards (PCBs) at the PCB Nexus event! Wh🔗 Join Us for PCB Nexus! 🚀ether you're a beginner or an expert, this event is designed to enhance your knowledge and skills.", image: des13 ,link : "https://docs.google.com/forms/d/e/1FAIpQLSeLykXDzXs-W8sIfO7J5sXDPXx48Nh6l2ev_tp3JATtqhfQgg/viewform?usp=header"},
    { id: 14, title: "Resume It || 12TH Feb", description: "Get ready to showcase your professional skills and stand out in the world of opportunities with Resume It, a premier resume competition under Yash 25.0. Whether you're a student preparing to enter the workforce or a young professional polishing your CV, this is your chance to shine and make an impact!", image: des14 ,link : "https://docs.google.com/forms/d/e/1FAIpQLSfvCdZjWVSyaWtUrDPdFyTGj272PUz8iCBRucVS_ZGdiPFFxg/viewform?usp=header"},
    { id: 15, title: "Robo Soccer || 13TH Feb", description: "Step into the future of football with Robo Soccer, an exciting event where technology and teamwork collide in thrilling robot soccer matches. Compete, innovate, and showcase your robotic creations in this high-tech sporting challenge.", image: des15 ,link : "https://docs.google.com/forms/d/e/1FAIpQLSfxx1NtvN6jOB7vQrUKqIHabJyzziG6iOO_-acy0ejn1JJkPQ/viewform?usp=header"},
    { id: 16, title: "Tech Art Fusion || 13TH Feb", description: "Unleash your imagination and design brilliance at Yash 25.0's Tech Art Fusion. Dive into the perfect blend of technology and artistry, where your creative concepts take center stage. Compete, innovate, and showcase your visionary masterpieces!", image: des16 ,link : "https://docs.google.com/forms/d/e/1FAIpQLSeIOCk352fUcpnz_XQRyFrO8M2oP2W56cQdF1viJCqKWQ8NAQ/viewform?usp=header"},
    { id: 17, title: "Turning Tussle || 10TH Feb", description: "Get Ready to Turn Up the Heat! 🚨Introducing the Turning Tussle Event 🎉Are you ready to put your machining skills to the test? 🤔 Do you have what it takes to craft precise components with lightning speed and precision? ⏱", image: des17 ,link : "https://docs.google.com/forms/d/e/1FAIpQLScW7kVXcBYKMk4mFbgo1vM4-YAjhEbfD2rRx1TN08M2uI2CBQ/viewform?usp=header"},
    { id: 18, title: "Visul Vibes || 9TH Feb", description: "🎥  Visual Vibes – Ignite Your Creativity! 🎨📸✨Step into Visual Vibes, where imagination takes center stage! Whether you’re into filmmaking, photography, design, or digital art, this is your chance to showcase your talent and compete for exciting rewards! 🚀🎬", image: des18 ,link : "https://docs.google.com/forms/d/e/1FAIpQLSfnOMhjZ4xGtGQZTMVb2NQVs0M4X5pFe0Ftz4CAPPpOpvNXnw/viewform?usp=header"}
  ];
  
  export default technicalEvents;
  